language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Gbx8jbRXgkzps0e370lbVbSa0OGFy1nLPerYh+2AWmf4ahsh6q00RIyKEX6WM00Fum46uZGOQ8vYcEBEoQkYvUXWuk+ATG1W8a2ylSE0oGALHnYANv8SLAb+jar5NOvpOeQ8qhYXkeiLrHHsHRV28ppEDwnJZhrF2fi70nwDbNVTMP9oPJTvDSG2xo9joS3HtR8pl6M+zd+6ivdEUndE/uWc8KKdORZDFiH2Gk7PxHYWKMlP9rC+ImsGFRmtZiYtFDUbqiPfYvUBN0VaMWmZ5F0hd4XayijwjwNHN+54waWShZSyQ84RAfUg/bZO52tOzYGgEyAI7o6J2Y9JVYbfPGuKuFWlPZEjr0YABHeXRIjot2lI8gptVzG5KMHnGzDbymVgABS85rCblf96c9yHpoqL9Wiftua+irr90gJdJ140Dd4p2rVJzmuZ0FQJIehrKXaK+XDFsaxksI6hb65Lca+VZdHzIdZ8LXo0PHZRfRvPnJNe7C8jX8MplTnee0pJV6g23wlJBsCONuD3Ub3iNGgJt7Z84kLyfxL5nFKslBf2cyhA1Z2kjLiWmlQnT202h0xcNdbIsh9nNW2zUbcqD1HM/lyYNwmu2dVcNNJdK7LR+hq5hFlI7IbNNa/TWF0AgXUBMy0tIWFAHbcFWeZrcmOOnQ0cMHfoNVW2o8Y6o28="
env:
  secure: "P7AWiox4cCMuNM8hiHkUjMAgkF5F7vhRRE8sKOwEpSlfec/a/P3ouYbe4Z/cPQ/r3U+nnJfcwtWBAgZhxUwvgWpkJLvloQSpSCwySE+9MItYfQLsCA7t+oqJcXewn0lPJw49kar0wmQZwOABTPN5RIcU+4G0Hrunrbr1pvDdDnJFYAQ+Vu5kcoUK3fRi8valgyCl3jcaQiEEXIY0V3ZtWbrMs1/b9oj7QSncgBHhtI1uKcLLp8ARXC4PKvtKhGlBST91OsNIXZdS5JhFaZTC4w64uZL5F5bZnnpSYPFDtX70YJ70Cpc+ByJdAPkNwHFHpikO2lhV5udYTimq7VfINfl9z5oSC5u4TE/jS5LWzVjMYRqJV8Gg+GMyHn/o33LdDbWowz+9YJve/CloXp3V06VA2ZisI5gjhO2efAemTagMlI9Q2QphDq6jnkO7GL9EIWxHnn8wijWXymUJb4vK+iQqIA3lch42xjIwA85Ufm5YLLjMMQ5Rg6T7RjPggYnUekfmkY/dSK8YtKkft+Ytf67Zx8KF+L1DG53aNGS08EkCoK3gnYNDow1tQkTrFhjz03mywLtbOJsqroPrNkIn2mgGbsYkS6yzA3lPMfiX1YfGcg3y/CFVLI3HxeU29U7gNn/Y+811Och+5LIzhA6WNOfeRyAvv832xKCMIJfdmww="
